#!/bin/sh
i3-msg '[workspace="1"]' move workspace to output DP-1
i3-msg '[workspace="2"]' move workspace to output DP-1
i3-msg '[workspace="3"]' move workspace to output DP-1
i3-msg '[workspace="4"]' move workspace to output DP-1
